export const projects = [
  {
    year: "2024",
    name: "andyyhy.com",
    description: "My personal website built with Next.js",
    demoLink: "https://andyyhy.com",
    sourceLink: "https://github.com/andyyhy/personal_web_v2",
  },
  {
    year: "2021",
    name: "Insta 485",
    description: "Instagram clone built with React and Flask",
    demoLink: "https://www.youtube.com/watch?v=4YtFGix3M2U",
    sourceLink: "https://github.com/andyyhy/Insta485",
  },
  {
    year: "2021",
    name: "Python Map Reduce",
    description: "Inspired by Google's MapReduce paper",
    demoLink: "https://github.com/andyyhy/MapReduce",
    sourceLink: "https://github.com/andyyhy/MapReduce",
  },
  {
    year: "2021",
    name: "Ask 485",
    description: "Scalable search engine like Google",
    demoLink: "https://github.com/andyyhy/Ask485",
    sourceLink: "https://github.com/andyyhy/Ask485",
  },
  {
    year: "2023",
    name: "A2-GO!",
    description: "AR experience inspired by Pokemon Go",
    demoLink: "https://www.youtube.com/watch?v=5P2DGmO1bVg",
    sourceLink: "https://www.unrealengine.com/en-US/unreal-engine-5",
  },
  {
    year: "2023",
    name: "Risky Roads",
    description: "VR platform for simulating driving scenarios",
    demoLink: "https://penga7.wixsite.com/riskyroads",
    sourceLink: "https://www.unrealengine.com/en-US/unreal-engine-5",
  },
  {
    year: "2023",
    name: "VR CSE Simulator",
    description: "VR Simulation of a room in the BBB at Umich",
    demoLink: "https://www.youtube.com/watch?v=5P2DGmO1bVg",
    sourceLink: "https://www.unrealengine.com/en-US/unreal-engine-5",
  },
  {
    year: "2022",
    name: "Text Emotion Classifier",
    description: "Classify emotions in Reddit comments with ML",
    demoLink: "https://github.com/andyyhy/ML-Text-Emotion-Classifier",
    sourceLink: "https://github.com/andyyhy/ML-Text-Emotion-Classifier",
  },
  {
    year: "2022",
    name: "Dog Breed Classifier",
    description: "Classify dog breeds using neural networks",
    demoLink: "https://github.com/andyyhy/ML-Dog-Breed-Classifier",
    sourceLink: "https://github.com/andyyhy/ML-Dog-Breed-Classifier",
  },
  {
    year: "2023",
    name: "Robotics Simulations",
    description: "Collection of Robotics projects",
    demoLink: "https://www.youtube.com/playlist?list=PL45gP5kWLladpLxLd-bQD_F9hxkMcYoHp",
    sourceLink: "https://github.com/andyyhy/Robotics",
  },
  {
    year: "2023",
    name: "VR Magic Show",
    description: "VR magic show built with Unreal Engine 5",
    demoLink: "https://www.youtube.com/watch?v=AMztRpmIl7M",
    sourceLink: "https://www.unrealengine.com/en-US/unreal-engine-5",
  },
  {
    year: "2023",
    name: "AR Vehicle Show",
    description: "AR Vehicle Show Built with Unity",
    demoLink: "https://www.youtube.com/shorts/47MTyTuCw5s",
    sourceLink: "https://unity.com/",
  },

  // Add more projects as needed
];
